name: Test Optional Dependencies

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extras: [[], ["jaeger"], ["zipkin"], ["all"]]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        if [ "${{ matrix.extras }}" != "[]" ]; then
          poetry install --extras "${{ matrix.extras }}"
        fi
    - name: Run tests
      run: poetry run pytest 